export const LOAD_GENERAL_POLL_QUESTION = 'LOAD_GENERAL_POLL_QUESTION';
export const LOAD_GENERAL_POLL_ANSWER = 'LOAD_GENERAL_POLL_ANSWER';
export const UPDATE_GENERAL_POLL = 'UPDATE_GENERAL_POLL';
export const UPDATE_GENERAL_POLL_ANSWER = 'UPDATE_GENERAL_POLL_ANSWER';
export const REMOVE_GENERAL_POLL = 'REMOVE_GENERAL_POLL';
export const REMOVE_GENERAL_ANSWER = 'REMOVE_GENERAL_POLL_ANSWER';